
package fiap.scj.ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MinhaSaudeImp1", targetNamespace = "http://soap.ws.scj.fiap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MinhaSaudeImp1 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retornaSituacao", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.RetornaSituacao")
    @ResponseWrapper(localName = "retornaSituacaoResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.RetornaSituacaoResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImp1/retornaSituacaoRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImp1/retornaSituacaoResponse")
    public String retornaSituacao(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param altura
     * @param peso
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularImc", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalcularImc")
    @ResponseWrapper(localName = "calcularImcResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalcularImcResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImp1/calcularImcRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImp1/calcularImcResponse")
    public String calcularImc(
        @WebParam(name = "altura", targetNamespace = "")
        float altura,
        @WebParam(name = "peso", targetNamespace = "")
        float peso);

}
