
package fiap.scj.ws.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MinhaSaudeImp1Service", targetNamespace = "http://soap.ws.scj.fiap/", wsdlLocation = "http://localhost:8080/minhasaude?wsdl")
public class MinhaSaudeImp1Service
    extends Service
{

    private final static URL MINHASAUDEIMP1SERVICE_WSDL_LOCATION;
    private final static WebServiceException MINHASAUDEIMP1SERVICE_EXCEPTION;
    private final static QName MINHASAUDEIMP1SERVICE_QNAME = new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImp1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/minhasaude?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MINHASAUDEIMP1SERVICE_WSDL_LOCATION = url;
        MINHASAUDEIMP1SERVICE_EXCEPTION = e;
    }

    public MinhaSaudeImp1Service() {
        super(__getWsdlLocation(), MINHASAUDEIMP1SERVICE_QNAME);
    }

    public MinhaSaudeImp1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MINHASAUDEIMP1SERVICE_QNAME, features);
    }

    public MinhaSaudeImp1Service(URL wsdlLocation) {
        super(wsdlLocation, MINHASAUDEIMP1SERVICE_QNAME);
    }

    public MinhaSaudeImp1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MINHASAUDEIMP1SERVICE_QNAME, features);
    }

    public MinhaSaudeImp1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinhaSaudeImp1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MinhaSaudeImp1
     */
    @WebEndpoint(name = "MinhaSaudeImp1Port")
    public MinhaSaudeImp1 getMinhaSaudeImp1Port() {
        return super.getPort(new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImp1Port"), MinhaSaudeImp1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MinhaSaudeImp1
     */
    @WebEndpoint(name = "MinhaSaudeImp1Port")
    public MinhaSaudeImp1 getMinhaSaudeImp1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImp1Port"), MinhaSaudeImp1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MINHASAUDEIMP1SERVICE_EXCEPTION!= null) {
            throw MINHASAUDEIMP1SERVICE_EXCEPTION;
        }
        return MINHASAUDEIMP1SERVICE_WSDL_LOCATION;
    }

}
